name: Terraform CI

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:

  terraform-check:
    name: Terraform Format and Validate
    runs-on: ubuntu-latest
    environment: DEV

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Init
        working-directory: environments/dev
        run: terraform init -backend=false

      - name: Terraform Validate
        working-directory: environments/dev
        run: terraform validate


  terraform-test:
    name: Terraform Tests
    runs-on: ubuntu-latest
    environment: DEV

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Test EC2 Module
        working-directory: modules/ec2
        run: |
          terraform init
          terraform test

      - name: Test S3 Module
        working-directory: modules/s3
        run: |
          terraform init
          terraform test


  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    environment: DEV

    permissions:
      id-token: write
      contents: read

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Terraform Init
        working-directory: environments/dev
        run: terraform init

      - name: Terraform Validate
        working-directory: environments/dev
        run: terraform validate
        
      - name: Terraform Plan
        working-directory: environments/dev
        run: |
          terraform plan \
            -var-file="terraform.tfvars" \
            -out="tfplan"